### ISSUE TITLE
Missing explicit IPMI channel numbers in set_bmc_credentials.sh

### ISSUE THREAD

**Issue by psalmia** [RackHD/on-http#211]
Some ipmitool commands in set_bmc_credentials.sh do not specify a channel number so the "currently used" channel is utilized. This causes problems in our hardware:

```
root@sut1-server2-pub:~# ipmitool user list
Get User Access command failed (channel 14, user 1): Invalid data field in request
root@sut1-server2-pub:~#
```
This causes the whole BMC credentials setting to fail.

The commands without a channel number are these:
```
cmdReturn=$(ipmitool user list)
...
cmdReturn1=$(ipmitool user summary)
```
The rest of the code suggests that channel 1 is to be used (judging from for example "ipmitool channel setaccess 1 $userNumber callin=on ipmi=on link=on privilege=4"), so the fix could be as simple as adding the channel number 1 to the commands listed above (e.g. "ipmitool user list 1" and "ipmitool user summary 1"). In our hw, using channel 1 works as expected.

Another option would be to figure out which channel works with something like this:
```
...
channel=''
function set_channel()
{
    for i in {1..15}; do
        ipmitool user list $i &>/dev/null
        status=$?
        if [ "$status" -eq "0" ] ; then
            channel=$i
            break
        fi
    done
}
set_channel
echo " Getting the user list from $channel"
cmdReturn=$(ipmitool user list $channel)
...
```

**Comment by heckj** [comment]
fyi @keedya @RackHD/corecommitters

**Comment by keedya** [comment]
Adding @uppalk1, @tannoa2

**Comment by uppalk1** [comment]
Agree with that. I will fix it and update.

**Comment by heckj** [comment]
@psalmia just out of curiosity, which hardware is this causing problems with? Is that something you can share?

**Comment by amymullins** [comment]
For reference, the effort to cover resolution/update for this issue is being tracked in PT : https://www.pivotaltracker.com/projects/1492890/stories/117244649

**Comment by psalmia** [comment]
The HW is Quanta STRATOS S210-X22RQ rackmount server.
On a related note, we have found a similar issue also in an HP ProLiant DL380p Generation8 server:
```
[root@S12 ~]# ipmitool user list
Get User Access command failed (channel 14, user 1): Parameter out of range
[root@S12 ~]# ipmitool user list 1
Get User Access command failed (channel 1, user 1): Parameter out of range
[root@S12 ~]# ipmitool user list 2
ID  Name             Callin  Link Auth  IPMI Msg   Channel Priv Limit
1   Administrator    true    false      true       ADMINISTRATOR
2   (Empty User)     true    false      false      NO ACCESS
3   (Empty User)     true    false      false      NO ACCESS
4   (Empty User)     true    false      false      NO ACCESS
5   (Empty User)     true    false      false      NO ACCESS
6   (Empty User)     true    false      false      NO ACCESS
7   (Empty User)     true    false      false      NO ACCESS
8   (Empty User)     true    false      false      NO ACCESS
9   (Empty User)     true    false      false      NO ACCESS
10  (Empty User)     true    false      false      NO ACCESS
11  (Empty User)     true    false      false      NO ACCESS
12  (Empty User)     true    false      false      NO ACCESS
[root@S12 ~]#
```
The difference is that even channel 1 is not working by default, so perhaps it would indeed be a good idea to figure out a working channel and use that.

**Comment by uppalk1** [comment]
Below PR has been created. Please take a look and see if it works. Thank you for the find and ideas on the fix.
https://github.com/RackHD/on-http/pull/234
