### ISSUE TITLE
/files/:filename/latest and /files/md5/:filename/latest missing in 1.1 southbound

### ISSUE THREAD

**Issue by zyoung51** [RackHD/on-http#215]
The routes to get a file by filename and get a file's md5sum by filename are both missing in the 1.1 southbound implementation.  Both of these routes are used by the download files task: https://github.com/RackHD/on-tasks/blob/master/lib/task-data/tasks/download-files.js

**Comment by jlongever** [comment]
fyi @RackHD/corecommitters @leoyjchang @cgx027

**Comment by anhou** [comment]
@zyoung51 it seems that these two APIs are missed during my initial summary of splitting southbound and northbound APIs. @WangWinson will help add these two APIs to southbound

**Comment by WangWinson** [comment]
see PR https://github.com/RackHD/on-http/pull/230

**Comment by zyoung51** [comment]
Thanks for the fix @WangWinson.
