### ISSUE TITLE
Uploading invalid sku pack crashes on-http.

### ISSUE THREAD

**Issue by rolandpoulter** [RackHD/on-http#220]
I created a sku pack file on Mac OS X using:
```
tar -cvzf virtualbox-pxe.tar.gz virtualbox-pxe/
```

Then I uploaded the file from a browser using superagent. 
![image](https://cloud.githubusercontent.com/assets/51327/14480738/9f58b070-00e0-11e6-950e-d4857b6875a2.png)

Causes the crash with the following error:
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:363:17)
```

**Comment by zyoung51** [comment]
@rolandpoulter I fixed an issue where the pipe chain was bombing out due to the invalid file being passed to it.  The API itself expects a content-type of application/x-www-form-urlencoded and not for the data to be encoded in multipart/form-data.

**Comment by rolandpoulter** [comment]
I don't think I can send files from the browser without using `multipart/form-data`. Need to double check that.
