### ISSUE TITLE
Only Southbound API displayed on swagger-ui

### ISSUE THREAD

**Issue by wangzhizheng** [RackHD/on-http#444]
When I opened the swagger-ui and found only Southbound API is displayed.
![pasted image at 2016_08_29 03_50 pm](https://cloud.githubusercontent.com/assets/10055093/18046090/2777ad92-6e11-11e6-9ba0-2ed24a6d0b7e.png)

**Comment by yyscamper** [comment]
Discussed with @wangzhizheng, the programmatic system is installed from debian package, the version is:
```
root@RackHD:/var/renasar/on-http# cat commitstring.txt
137bb9d.2016-08-25 15:38:01 -0700.Merge pull request #439 from VulpesArtificem/rack-event
``` 

I guess the swagger-ui installation fails while building debian package.

**Comment by wangzhizheng** [comment]
When I disabled my firewall and restart the on-http service, all api displayed on the swagger-ui.
I think it is caused by my firewall configuration.

**Comment by brianparry** [comment]
@yyscamper @wangzhizheng This issue has been observed a number of different times under different circumstances.  We definitely should investigate it.  I think I'd start with removing the southbound swagger file altogether since it is not used.

**Comment by BillyAbildgaard** [comment]
link to story in the Stryker backlog:

https://www.pivotaltracker.com/story/show/129367841

**Comment by heckj** [comment]
I've seen this in the past too (probably the mention that @brianparry was referencing). Wasn't able to get a consistent reproduction of the issue, and noted that when I restarted the services, this sometimes disappeared. My hypothesis is that swagger-ui doesn't like to represent multiple endpoints in its documentation - only shows one (north or south), in a non-deterministic fashion
