### ISSUE TITLE
On ECS node, get_driveid.js. is not creating the virtualDisk attribute

### ISSUE THREAD

**Issue by ytjohn** [RackHD/on-http#571]
get_driveid.js. is not creating the virtualDisk attribute on an EMC ECS node.  It seems to work fine in all other instances we tried. I have looked over the code, but I don't see how devName can get populated but not virtualDisk.

https://github.com/RackHD/on-http/blob/master/data/templates/get_driveid.js#L263

This is mainly only an issue because [secure_erase.py](https://github.com/RackHD/on-http/blob/master/data/templates/secure_erase.py#L365) expects the virtualDisk attribute to exist.

Here's a snipped of my driveid catalog showing the DOM with virtualDisk and two drives that did not get the attribute.

```
{
    "createdAt": "2017-01-26T19:31:24.241Z",
    "data": [
                {
            "devName": "sdp",
            "esxiWwid": "naa.5000cca23bdb6b26",
            "identifier": 23,
            "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHY9ULX",
            "scsiId": "0:0:15:0"
        },
        {
            "devName": "sda",
            "esxiWwid": "t10.ATA_____SATADOM2DSL_3ME__________________________20151216AAAA00000292",
            "identifier": 24,
            "linuxWwid": "/dev/disk/by-id/ata-SATADOM-SL_3ME_20151216AAAA00000292",
            "scsiId": "2:0:0:0",
            "virtualDisk": ""
        },
        {
            "devName": "sdb",
            "esxiWwid": "naa.5000cca04dab3ca8",
            "identifier": 25,
            "linuxWwid": "/dev/disk/by-id/scsi-35000cca04dab3ca8",
            "scsiId": "0:0:0:0"
        }
    ],
    "id": "60794525-0f4c-4efd-9497-48208ab5de49",
    "node": "588a4e1f860614391849775f",
    "source": "driveId",
    "updatedAt": "2017-01-26T19:31:24.241Z"
}
```

**Comment by johren** [comment]
https://rackhd.atlassian.net/browse/RAC-4098

**Comment by pengz1** [comment]
@ytjohn 
For sdp and sdb, are they in JBOD status?

**Comment by pengz1** [comment]
@ytjohn 
I push PR to fix this issue:
https://github.com/RackHD/on-http/pull/581
Could you help to try if this works for you?

**Comment by ytjohn** [comment]
I will give it a shot. And yes, these are jbod drives.

**Comment by pscharla** [comment]
Looks like associated RAC issue is closed out now so closing this github issue.
