### ISSUE TITLE
some driveId catalogs may not have virtualDisk attribute

### ISSUE THREAD

**Issue by ytjohn** [RackHD/on-http#572]
This is related to #571. A catalog might get created without the virtualDisk attribute. I think ideally, we want to fix the catalog creation. But for me, I made the following change to [secure_erase.py](https://github.com/RackHD/on-http/blob/master/data/templates/secure_erase.py#L365) in order to not have the script crash.

    disk_list_without_raid = []
    for disk_argument in disk_argument_list:
        # if virtualDisk doesn't exit, push disk directly into disk list
        if "virtualDisk" not in disk_argument.keys():
            disk_argument["virtualDisk"] = ''

        if not disk_argument["virtualDisk"]:
            # disk_list_without_raid.append("/dev/" + disk_argument["diskName"])
            disk_list_without_raid.append(disk_argument["diskName"])
        else:
            command = [raid_tool, "/c0", "set", "jbod=on"]
            subprocess.check_output(command, shell=False)
            command = [raid_tool, disk_argument["virtualDisk"], "del", "force"]
            subprocess.check_output(command, shell=False)
            disk_list_without_raid += create_jbod(disk_argument, raid_tool)
    return disk_list_without_raid

@pengz1, since you are most active on both of these files, I've tagged you on both issues.

**Comment by johren** [comment]
Opened https://rackhd.atlassian.net/browse/RAC-4099

**Comment by leoyjchang** [comment]
@ytjohn Glad to see you start using secure erase feature. @pengz1 from Shanghai team is the main author for this feature. Feel free to tell us any issue/feedback in this area.

**Comment by pscharla** [comment]
Looks like the RAC issue is now closed out so closing this github issue.
