### ISSUE TITLE
Additional Schema Definitions in Swagger for Workflows

### ISSUE THREAD

**Issue by king-jam** [RackHD/on-http#596]
The Monorail 2.0 Swagger file lacks the necessary schemas found in the documentation. Though the swagger is useful to generate clients, it lacks definition for plug and play usage to call workflows because lack of definition here:
https://github.com/RackHD/on-http/blob/master/static/monorail-2.0.yaml#L173
not match with:
http://rackhd.readthedocs.io/en/latest/rackhd/install_os.html#non-windows-os-installation-workflow-payload

**Comment by lanchongyizu** [comment]
@RackHD/corecommitters Do we need to enhance it?

**Comment by yyscamper** [comment]
The challenge of workflow schema is it is totally dynamic, different user input should use different schema.
Even for the similar OS installation, the "dynamic" is still existing as different OS support different kind of parameters. 

Actually the schema validation for workflow API has been enabled, please see the "Upfront Schema Validation" section in this link http://rackhd.readthedocs.io/en/latest/rackhd/tasks.html#task-schema . The difference with other APIs is that we don't use Swagger schema.

As for the API doc that generated from Swagger, we also have similar doc for task (not graph yet), please refer to http://rackhd.readthedocs.io/en/latest/rackhd/tasks.html#task-annotation

**Comment by pscharla** [comment]
Created this RAC to replace this github issue:
https://rackhd.atlassian.net/browse/RAC-4725

and closing this out. Please continue discussion in jira.
