### ISSUE TITLE
Redfish API Task ID return via OEM BootImage command

### ISSUE THREAD

**Issue by king-jam** [RackHD/on-http#597]
RackHD OEM command Boot Image aka Install OS doesn't respond with the TaskID so the only way to check the status of an install workflow is by hitting the TaskService and iteraing every task for a matching system ID using the OEM->RackHD->SystemID. Depending on the number of tasks, this could be a scaling issue for a consumer.

**Comment by amymullins** [comment]
github issues will soon be redirected to Jira.  

Opened Jira issue for tracking: https://rackhd.atlassian.net/browse/RAC-4332

**Comment by king-jam** [comment]
issue exists mainly around here in the Swagger file. https://github.com/RackHD/on-http/blob/8da2897ffc2d9db904e1224704bb22f8d08b2403/static/redfish.yaml#L613

The success payload is generic https://github.com/RackHD/on-http/blob/8da2897ffc2d9db904e1224704bb22f8d08b2403/static/redfish.yaml#L636 which means a generated client (Java) will create a function with a 'void' return.

**Comment by pscharla** [comment]
Looks like the above RAC issue is now closed out so closing out this github issue.
